### PR TITLE
First smoothing CMT integration

### PR DESCRIPTION
**Pull request by jorana**
**What is the problem / what does the code in this PR do**
The new [implementation of the CMT ](https://github.com/XENONnT/straxen/pull/220) still has some starters issues. This a first attempt to fix a few and allow for better integration into the straxen mainframe.
It is a very important tool as we are otherwise referring to very un-elegant solutions that may become a nightmare to manage.

In contrast to what I have been advocaing in the past, I don't thing that we have to inherrit the strax-parent. Not loading the parrent creates an extra layer between the user and the operations that allow one to delete/edit stuff in the database.

**Can you briefly describe how it works?**
What have I changed:

- Integrate the CMT in the existing functions `get_elife` and `get_to_pe`
- Switch to the CMT for the main nT context.
- I basically left the CMT class at it is although there are still some things that can be improved.
- Raise more instructive Error Messages where possible.
- Fix the test to not use CMT as it does require quite some setting up to do.

**Things that are still pending**
- It is really slow. If we spend 5 minutes each run loading gains, its one of the slowest algos in strax/straxen.
- There is no restriction on reading/writing. This can become extremely nasty if someone ‘by accident’ drops one of the collections.
- It’s not really an harmonious marriage with straxen. I would like to do the init in the context but at the moment I haven’t been able to do a proper job.
- The structure is a big load on the databases.

### CODE REVIEW

**Comment by ahiguera-mx** [comment]
Hi @jorana 

Sorry in advance but I'm getting used to GitHub so not sure how to add question for specific parts of your PR, but I would do my best

https://github.com/XENONnT/straxen/blob/update_cmt/straxen/gain_elife_models.py
Here you are adding CMT as an option to be used as a model_type, but you are keeping the same options as in the original gain_models.py,  
https://github.com/XENONnT/straxen/blob/b15a467b9311a981341e2ead84ee8b77c7ea8dfd/straxen/gain_elife_models.py#L47

**Comment by jorana** [comment]
Hi Aaron, 

>currently CMT can do exactly the same, so I'm not sure why we want to duplicate this, and you are doing the same for get_elife. this would make harder to debug since there is the option of use the old implementation and CMT.

Sure, for the moment I focused on the gains but we can think about how we do this for the elife later too. As you might have seen I only changed the option for the gains for now. At the moment, I don't think it makes sense to call a service that just returns the input (i.e. the constant) one provided already when calling that service. But we can do some rethinking on that.

> gain_elife_models.py calls CMT and duplicates what CMT can do
I think this is your most important concern. So the reason why I went this way is to provide the following:
- Backward compatibility to what we have been using so far. Otherwise it's unnecessarily hard to be backward compatible.
- You would be doing steps initializing the CMT et cetera which is needed.
- In the future we might want to indeed go the way that you were proposing when we have further optimized the CMT. In fact, we might want to consider doing a somewhat leaner init of the CMT such that we don’t unnecessarily loose time there.

Let me also add the comments I just posted in slac:
> More importantly, you only are going to use CMT when doing reprocessing, daily user that does mostly analysis does not have to worried about “slowness”
Well every step will be affected, you want to be using the same gains. This means that online-processing and user processing is affected. If one wants to do some optimization of a plugin needing gains, this will become very tedious. Even the simulations might be affected unless someone disables this implementation.

There is probably room for improvement (for future PRs?):
 - Most likely you have checked this, but does indexing of the collections help at all? 
 - Furthermore, can we do some smart query to only get e.g. 10 points that are closest to the requested data?


> There is no restriction on reading/writing. This can become extremely nasty if someone ‘by accident’ drops one of the collections.
Ok, good, that is in contrast to what I read in cell 7 here: https://github.com/XENONnT/analysiscode/blob/master/StraxTests/corrections_strax_test.ipynb but I'm glad that this is not an issue!

> but again I’m not sure of the cost vs benefit
Maybe I can put this in context by processing an exemplary run

> having the data stored and accessing through a DB makes bookkeeping easier, if we don’t rely on the info in our DB then why are they in the first place (edited) 
I understand that the bookkeeping is easier but if things start breaking, we know where to look ;)


> Sorry in advance, but I'm getting used to GitHub so I'm not sure how to add comments for specific parts of your PR, but I would do my best
Don't worry, it makes most sense to add the comments on the code itself if it's specific. Click here
afbeelding
and then click on the line you want to say something about. E.g.:
afbeelding
(don't forget to submit the review in the upper left corner)

**Comment by jorana** [comment]
@ahiguera-mx , hopefully I didn't forget something but I think 5b5f42c should be what we discussed.

**Comment by ahiguera-mx** [comment]
Thanks @jorana, I did a small tweak of the deprecation waring

**Comment by jorana** [comment]
> 
> 
> Thanks @jorana, I did a small tweak of the deprecation waring

Ah, good catch, looks good!

**Pull request merged**
